# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 18:28
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sore_Throat', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=128, null=True)),
                ('Diastolic_Blood_Pressure', models.DecimalField(decimal_places=2, default='', max_digits=5, validators=[accounts.models.validate_bp_low])),
                ('Systolic_Blood_Pressure', models.DecimalField(decimal_places=2, default='', max_digits=5, validators=[accounts.models.validate_bp_high])),
                ('Respiratory_rate', models.DecimalField(decimal_places=2, default='', max_digits=5, validators=[accounts.models.validate_rr])),
                ('Pulse_rate', models.DecimalField(decimal_places=2, default='', max_digits=5, validators=[accounts.models.validate_pr])),
                ('Temperature', models.DecimalField(decimal_places=2, default='', max_digits=5, validators=[accounts.models.validate_temp])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
