# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180211_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisinfo',
            name='So_Throat',
            field=models.IntegerField(blank=True, choices=[('Y', 1), ('N', 0)], null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisinfo',
            name='Sor_Throat',
            field=models.IntegerField(blank=True, choices=[('Y', 1), ('N', 0)], null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisinfo',
            name='Sore_Throat',
            field=models.IntegerField(blank=True, choices=[('Y', 1), ('N', 0)], null=True),
        ),
    ]
