# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180211_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisinfo',
            name='So_Throat',
        ),
        migrations.RemoveField(
            model_name='diagnosisinfo',
            name='Sor_Throat',
        ),
        migrations.AddField(
            model_name='diagnosisinfo',
            name='Constipation',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisinfo',
            name='Rashes',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisinfo',
            name='Sore_Throat',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, null=True),
        ),
    ]
